### ISSUE TITLE
ProvisioningMacAddresses cannot be obtained correctly

### ISSUE THREAD

**Issue by zhouhao3** [openshift/cluster-baremetal-operator#311]
Starting with ocp4.11.5 (cluster-baremetal-operator #282  ), IPI deployment fails.

The failure phenomenon is that  the metal3 deployment node cannot be successfully deployed  in the master, the specific error is that its init container `metal3-static-ip-set` will have some errors:
```
» oc logs metal3-586fd74b5d-7mr4j -n openshift-machine-api -c metal3-static-ip-set
+ '[' -z 192.168.20.3/24 ']'
+ '[' -z '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ echo 'ERROR: Could not find suitable interface for "192.168.20.3/24"'
ERROR: Could not find suitable interface for "192.168.20.3/24"
+ exit 1
```

After verification, it is found that the value of `PROVISIONING_MACS` in deploy is empty, and this value should be obtained and assigned by cluster-baremetal-operator.
```
      initContainers:
      - command:
        - /set-static-ip
        env:
        - name: PROVISIONING_IP
          value: 192.168.20.3/24
        - name: PROVISIONING_INTERFACE
        - name: PROVISIONING_MACS
        - name: HTTP_PROXY

```

Starting from #282, `bmhNames` will be obtained through `ProviderID` instead of directly using the "master", but I found from the log that the `ProviderID` of the node is `Unschedulable:false` when the error occurs, so the return value of `getHostByProviderId` is empty, which causes `ProvisioningMacAddresses` not to be assigned.
